### ISSUE TITLE
Copying

### ISSUE THREAD

**Issue by vutondesign** [redmangospros/cheatmojji#2]
This is a copy of https://gist.github.com/roachhd/1f029bd4b50b8a524f3c

**Comment by redmangospros** [comment]
`THIS MIGHT BE A COPY! BUT,  GITUB IS OPEN SOURCE AND THAT GIST IS ALLOWED FOR USE`

**Comment by vutondesign** [comment]
> GITUB IS OPEN SOURCE AND THAT GIST IS ALLOWED FOR USE

Yes, however that doesn't mean you can copy others work and claim that it's yours. It also may be open source, but the repo license changes a lot of things...

**Comment by redmangospros** [comment]
I Nevr Sajd it is my

**Comment by vutondesign** [comment]
>Some Emojjis from : https://gist.github.com/roachhd/1f029bd4b50b8a524f3c

*cough cough* 

> ALL Emojjis from : https://gist.github.com/roachhd/1f029bd4b50b8a524f3c
